### ISSUE TITLE
Idea: let chat GPT help me with JSF code

### ISSUE THREAD

**Issue by ivy-rew** [axonivy-market/openai-connector#11]
chat GPT knows how to read and write JSF code: so let's use it as low-code assistant in JSF dialogs

- Explain code: ![chat-gpt_explain](https://github.com/axonivy-market/openai-connector/assets/15085693/162676c0-baa4-4c6a-8494-3f57344f3c07)
- Fix my error: ![chat-gpt_fixesYourCode](https://github.com/axonivy-market/openai-connector/assets/15085693/2f35da83-fb14-46cb-a3c6-eecb38105278)
- Help me 2 code: simple calendar
![chat-gpt_code4me](https://github.com/axonivy-market/openai-connector/assets/15085693/34de7742-869c-4e5a-a366-6c4a756026a1)
- Help to write new code: menu  ![chat-gpt_codeMenu](https://github.com/axonivy-market/openai-connector/assets/15085693/7d578433-7db1-42a8-8b9e-1f2bd9b46997)

There are similar plugins out there for vs-code: https://marketplace.visualstudio.com/items?itemName=timkmecl.chatgpt

**Comment by ivy-rew** [comment]
> I think im not good enought at JSF becuase in the `Fix my error:` point i dont see what it changed exactly sweat_smile

you don't? I feel like this extension will be very helpful, also for us core developers ;-)
However, I forgot to quote my El-expression within the `actionListener` ... chat GPT found and fixed that for me.

**Comment by jackra1n** [comment]
oh wow thats a small one 😄 
highlighting would also help here almost as much as GTP tho 😉

**Comment by ivy-rew** [comment]
do you feel the spirit of pentecoast ?
![chat-gpt-explain](https://github.com/axonivy-market/openai-connector/assets/15085693/0779fb12-fe0c-4e18-8fec-68153abc8c76)

**Comment by andreasbalsiger** [comment]
I asked ChatGPT to make e joke about the spirit of pentecoast...
![image](https://github.com/axonivy-market/openai-connector/assets/75735026/ac4b9e7c-b596-4808-b3c4-1a0bdbef3440)

:)

**Comment by ivy-rew** [comment]
feeling lazy and over-strained from the code in error? let chat gtp fix it for you
 
![chat-gpt-fix](https://github.com/axonivy-market/openai-connector/assets/15085693/4c3e7130-d406-4f5f-aaa2-b3ac1eeb4cf0)

**Comment by ivy-rew** [comment]
ready to stop writing new complex statements? 
isn't it easier to give natural language commands to your Chat GPT assistant?
![chat-gpt-insert](https://github.com/axonivy-market/openai-connector/assets/15085693/b05f9289-9e99-4697-b2ec-b907c4a5550b)

**Comment by ivy-rew** [comment]
wanna get fast feedback on your code before shipping it through the official review?
![chat-gpt-freestyle](https://github.com/axonivy-market/openai-connector/assets/15085693/7bdabf2d-ce29-4f04-a32c-87cf7fb65657)

**Comment by ivy-rew** [comment]
we're not bound to jsf-dialogs ... let's play with processes: next time you may just record the kick-off meeting with a customer ... and chat-gpt draws the process you were talking about :sweat_smile: 
![chat-gpt-process2](https://github.com/axonivy-market/openai-connector/assets/15085693/e5a2e8b1-9c1f-4b15-8160-3c97c053074b)
![chat-gpt-processes](https://github.com/axonivy-market/openai-connector/assets/15085693/d2798a8f-805f-422c-9e3c-8afe425a7ae8)

**Comment by ivy-rew** [comment]
onboarding a first alpha-version to gather feedback: https://github.com/axonivy-market/market/pull/301

**Comment by ivy-rew** [comment]
released first alpha: https://market.axonivy.com/openai-assistant#tab-description
feel free to open new issues for feature wishes or bug reports
