### ISSUE TITLE
small fixes

### ISSUE THREAD

**Issue by thomaszehetner** [axonivy-market/openai-connector#28]
- right mouse in process modeller for windows not working
- screen is not showing button in explain usecase because content is too big/overflow. can be tested with simple process - 1 acitivity

**Comment by ivy-rew** [comment]
right mouse; must be fixed in the GLSP process editor which is hard to supply for all ivy versions that the ChatGPT assistant currently supports -> so I'd opt for a 'chat-gpt' button in the generic toolbar menu of the IDE. Or if that doesn't work, contribute it to the normal menu.

**Comment by ivy-rew** [comment]
improved: all your features should work with the next version https://github.com/axonivy-market/openai-connector/pull/29

**Comment by ivy-rew** [comment]
done: released as chatGpt.assistance:10.0.6 -> https://market.axonivy.com/openai-assistant
