### ISSUE TITLE
Model_not_found error

### ISSUE THREAD

**Issue by mao-aavn** [axonivy-market/openai-connector#42]
Hi there,
I got the below error in my first try with the ChatGPT Assistant pluggin, can you please have a look ?

![image](https://github.com/axonivy-market/openai-connector/assets/136697041/49954712-a11a-44d9-a929-531618c8698b)

Reproduce:
- Open Axon.Ivy Version: 10.0.17 (Weissfluh)
- Install the ChatGPT Assistant version 10.0.8 pluggin, from the designer's Axon.Ivy market.
- Set apiKey as the image
![image](https://github.com/axonivy-market/openai-connector/assets/136697041/7e630009-df4e-45ca-a0e3-b89ea1497ea4)
- Select a jsf tag on xhtml view, and click on ChatGPT Assistant icon > Explain 
- Finally it shows the error dialog

Thanks.

**Comment by ivy-rew** [comment]
Hi @ivy-sgi 
can we address this in the current sprint? 
seems as if we simply have to switch our default engine.
more and more users are running into this problem https://community.axonivy.com/d/606-error-on-using-chatgpt-assistant

**Comment by ivy-rew** [comment]
I assume the the "edit" context action still works; as it uses the davinci4 model: https://github.com/axonivy-market/openai-connector/blob/master/openai-assistant/src/com/axonivy/connector/openai/assistant/ChatGptRequest.java#L72
while all other actions lead to the now deprecated davinci3 model: https://github.com/axonivy-market/openai-connector/blob/master/openai-assistant/src/com/axonivy/connector/openai/assistant/ChatGptRequest.java#L51

**Comment by ivy-rew** [comment]
fixed with https://github.com/axonivy-market/openai-connector/pull/43
released as 10.0.9: https://market.axonivy.com/openai-assistant
