### ISSUE TITLE
Insert & edit problem with ChatGPT assistant

### ISSUE THREAD

**Issue by linhpd-axonivy** [axonivy-market/openai-connector#61]
This error was reported by Thomas Z. - Sabine have retested it with Designer v10.0.21 and ChatGPT assistant v 10.0.10. and found the same behaviour.

When trying to use the “insert” functionality of the ChatGPT assistant some strange behaviour appeared:
![image](https://github.com/user-attachments/assets/dbb32f41-9969-4fa9-b938-b6a070feb7b0)
![image](https://github.com/user-attachments/assets/c7b748f0-6a59-479f-bf97-e8190ecf6ca4)
Now no insert happens but a replace:
![image](https://github.com/user-attachments/assets/084ff6cc-67cd-4a13-92ff-b234526018b0)
When using the edit functionality this happens (error message “model not found” - when changing the model nothing changed, ie same error message).
![image](https://github.com/user-attachments/assets/ba54731f-0b80-4cfd-bd09-26b779b7f844)

**Comment by linhpd-axonivy** [comment]
Hi @ivy-rew ,
Do you have any ideas on this error?

**Comment by ivy-rew** [comment]
Please state a concrete question if you need support.
- insert; looks like a programming error introduced by the recent changes ... since it wasn't present in the previous versions.
- edit; is simply using a model which is no longer support ... just like the error says.

**Comment by linhpd-axonivy** [comment]
I mean the insert feature. I tested it with an older version (10.0.9) and it has the same error. I cannot run the older version. I think we should make some enhancements to the insert feature. Do we have any way to determine where we should insert the ChatGPT response content into the existing content?

**Comment by ivy-rew** [comment]
I think I'd change the 'prompt' until chat-gpt respondes with the full content. I think now we simply ship a static 'insert' prefix or something the like. Maybe we have to be more specific and also state that we require the result to contain a merged result.

**Comment by linhpd-axonivy** [comment]
Sabine created a [ticket](https://1ivy.atlassian.net/browse/MARP-555) for the Octopus team to handle the issue. Could you explain more details about your ideas? I will implement it.

**Comment by ivy-rew** [comment]
I think we can make ChatGpt respond with the new item already inserted, if we send the correct prompt.
It worked that way from the start; see https://github.com/axonivy-market/openai-connector/issues/11#issuecomment-1564315624
Therefore I assume that the AI just changed its way to respond.... what comes natural.

So the work to for you is to experiment with various prompt inputs, until you get the results as we need it.
If language is your limit, try to use structure-prompts (#33) in order to provide more context how you want chat GPT to respond .

**Comment by linhpd-axonivy** [comment]
Hi @ivy-rew ,
I've created a new PR to handle this issue. Can you take a look at it? https://github.com/axonivy-market/openai-connector/pull/69
